package vn.com.courseman.model;

import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.AttrRef;
import domainapp.basics.model.meta.DAssoc;
import domainapp.basics.model.meta.DAssoc.AssocEndType;
import domainapp.basics.model.meta.DAssoc.AssocType;
import domainapp.basics.model.meta.DAssoc.Associate;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DAttr.Type;
import domainapp.basics.model.meta.DClass;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.model.meta.MetaConstants;
import domainapp.basics.util.Tuple;
import vn.com.courseman.model.reports.WatermelonByOriginReport;

/**
 * A domain class whose objects are origin names. This class is used as the
 * <code>allowedValues</code> of the domain attributes of other domain classes
 * (e.g. Watermelon.origin).
 * 
 * <p>
 * Method <code>toString</code> overrides <code>Object.toString</code> to return
 * the string representation of a city name which is expected by the
 * application.
 * 
 * @author dmle
 *
 */
@DClass(schema = "watermelon")
public class Origin {
	public static final String A_name = "name";
	public static final String A_rptWatermelonByOrigin = "rptWatermelonByOrigin";
	@DAttr(name = "id", id = true, auto = true, length = 3, mutable = false, optional = false, type = Type.Integer)
	private int id;
	private static int idCounter;

	@DAttr(name = "name", type = Type.String, length = 20, optional = false)
	private String name;

	@DAttr(name = "watermelon", type = Type.Domain, serialisable = false)
	@DAssoc(ascName = "watermelon-has-origin", role = "origin", ascType = AssocType.One2Many, endType = AssocEndType.One, associate = @Associate(type = Watermelon.class, cardMin = 1, cardMax = MetaConstants.CARD_MORE, determinant = true))
	private Watermelon watermelon;
	
	// v5.0: to realise link to report
	  @DAttr(name=A_rptWatermelonByOrigin,type=Type.Domain, serialisable=false, 
	      // IMPORTANT: set virtual=true to exclude this attribute from the object state
	      // (avoiding the view having to load this attribute's value from data source)
	      virtual=true)
	  private WatermelonByOriginReport rptWatermelonByOrigin;
	  
	// from object form: Student is not included
	@DOpt(type = DOpt.Type.ObjectFormConstructor)
	@DOpt(type = DOpt.Type.RequiredConstructor)
	public Origin(@AttrRef("name") String cityName) {
		this(null, cityName, null);
	}

	// from object form: Student is included
	@DOpt(type = DOpt.Type.ObjectFormConstructor)
	public Origin(@AttrRef("name") String cityName, @AttrRef("watermelon") Watermelon watermelon) {
		this(null, cityName, watermelon);
	}

	// from data source
	@DOpt(type = DOpt.Type.DataSourceConstructor)
	public Origin(@AttrRef("id") Integer id, @AttrRef("name") String cityName) {
		this(id, cityName, null);
	}

	// based constructor (used by others)
	private Origin(Integer id, String cityName, Watermelon watermelon) {
		this.id = nextId(id);
		this.name = cityName;
		this.watermelon = watermelon;
	}

	private static int nextId(Integer currID) {
		if (currID == null) {
			idCounter++;
			return idCounter;
		} else {
			int num = currID.intValue();
			if (num > idCounter)
				idCounter = num;

			return currID;
		}
	}

	/**
	 * @requires minVal != null /\ maxVal != null
	 * @effects update the auto-generated value of attribute <tt>attrib</tt>,
	 *          specified for <tt>derivingValue</tt>, using <tt>minVal, maxVal</tt>
	 */
	@DOpt(type = DOpt.Type.AutoAttributeValueSynchroniser)
	public static void updateAutoGeneratedValue(DAttr attrib, Tuple derivingValue, Object minVal, Object maxVal)
			throws ConstraintViolationException {

		if (minVal != null && maxVal != null) {
			// TODO: update this for the correct attribute if there are more than one auto
			// attributes of this class
			int maxIdVal = (Integer) maxVal;
			if (maxIdVal > idCounter)
				idCounter = maxIdVal;
		}
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Watermelon getWatermelon() {
		return watermelon;
	}

	@DOpt(type = DOpt.Type.LinkAdderNew)
	public void setNewWatermelon(Watermelon watermelon) {
		this.watermelon = watermelon;
		// do other updates here (if needed)
	}

	public void setWatermelon(Watermelon watermelon) {
		this.watermelon = watermelon;
	}

	@Override
	public String toString() {
		return name;
	}
}
